# Generated by Django 5.0.7 on 2024-08-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullname',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fullname',
            name='phone_number',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fullname',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
